version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2182:2181"  # Update to expose ZooKeeper on port 2182
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "./volumes/zookeeper/data:/bitnami/zookeeper"
    networks:
      - kafka

  kafka-broker-1:
    image: bitnami/kafka:latest
    hostname: kafka-broker-1
    container_name: kafka-broker-1
    ports:
      - "19092:19092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
      - KAFKA_LISTENERS=PLAINTEXT://:9092,LISTENER_LOCAL://:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./volumes/kafka/broker-1:/bitnami/kafka"
    depends_on:
      - zookeeper
    networks:
      - kafka

  kafka-broker-2:
    image: bitnami/kafka:latest
    hostname: kafka-broker-2
    container_name: kafka-broker-2
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9092,LISTENER_LOCAL://localhost:29092
      - KAFKA_LISTENERS=PLAINTEXT://:9092,LISTENER_LOCAL://:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./volumes/kafka/broker-2:/bitnami/kafka"
    depends_on:
      - zookeeper
    networks:
      - kafka

  kafka-broker-3:
    image: bitnami/kafka:latest
    hostname: kafka-broker-3
    container_name: kafka-broker-3
    ports:
      - "39092:39092"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-3:9092,LISTENER_LOCAL://localhost:39092
      - KAFKA_LISTENERS=PLAINTEXT://:9092,LISTENER_LOCAL://:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./volumes/kafka/broker-3:/bitnami/kafka"
    depends_on:
      - zookeeper
    networks:
      - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    platform: linux/amd64
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_ADVERTISED_LISTENERS: http://localhost:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: >
        PLAINTEXT://kafka-broker-1:9092,
        PLAINTEXT://kafka-broker-2:9092,
        PLAINTEXT://kafka-broker-3:9092
      SCHEMA_REGISTRY_DEBUG: 'true'
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
