apiVersion: apps/v1
kind: Deployment
metadata:
  name: raja-ongkir-app-deployment
  namespace: default
  labels:
    app: raja-ongkir-app-deployment
spec:
  selector:
    matchLabels:
      app: raja-ongkir-app-deployment
  template:
    metadata:
      labels:
        app: raja-ongkir-app-deployment
    spec:
      containers:
        - name: raja-ongkir-app
          image: asia-southeast2-docker.pkg.dev/civil-hash-446108-e1/com-multiwarehouse-app-repository/raja.ongkir.app:1.0
          ports:
            - containerPort: 3003
          env:
            - name: HOST
              value: "0.0.0.0"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: raja-ongkir-app
  namespace: default
  labels:
    app: raja-ongkir-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: raja-ongkir-app-deployment
  ports:
    - name: raja-ongkir-service-port
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
