apiVersion: apps/v1
kind: Deployment
metadata:
  name: raja-ongkir
  labels:
    app: raja-ongkir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raja-ongkir
  template:
    metadata:
      labels:
        app: raja-ongkir
    spec:
      containers:
        - name: raja-ongkir
          image: asia-southeast2-docker.pkg.dev/civil-hash-446108-e1/com-multiwarehouse-app-repository/raja-ongkir-app:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: raja-ongkir-service
spec:
  type: LoadBalancer
  selector:
    app: raja-ongkir
  ports:
    - name: raja-ongkir-service-port
      protocol: TCP
      port: 3003
